### ISSUE TITLE
Linux: hust-login.py better commandline support

### ISSUE THREAD

**Issue by recolic** [Cra1gTucker/hust-login#1]
it's better to run hust-login.py with `hust-login.py -u u201614444 -p myPassword` or `hust-login.py -u u201614444 -p # read from stdin`. It's not common to read username from stdin, which makes scripting harder.

**Comment by Cra1gTucker** [comment]
Tried to use `argparse` module to deal with this, done but **not tested**(not in campus at the moment), now the usage is as you requested. If no arguments passed, still functions as previously.

**Comment by recolic** [comment]
thanks a lot for that

**Comment by Cra1gTucker** [comment]
tested, no problem, closing issue
